import { nanoid } from 'nanoid'
import { LocationScopedRepo } from './base-repo'

export type EnrollmentStatus = 'active' | 'completed'

export interface Enrollment {
  id: string
  location_id: string
  course_id: string
  contact_id: string | null
  token: string
  status: string
  enrolled_at: string | null
  completed_at: string | null
  created_at: string
}

export interface EnrollmentInput {
  courseId: string
  contactId?: string | null
  /** The unguessable public-link token, generated by the caller. */
  token: string
}

/**
 * Enrollments tie a contact to a course and mint the tokenized link to the public
 * course player. The enrollment carries no progress figure of its own — progress
 * is derived from the lesson_completions the student actually records — so the
 * only state it owns is `status`, which flips to `completed` (and stamps
 * `completed_at`) the moment the last lesson is finished. `getByToken` is the
 * unauthenticated public lookup, still bound to the location in the URL so it
 * stays tenancy-safe.
 */
export class EnrollmentsRepo extends LocationScopedRepo {
  listByCourse(courseId: string): Promise<Enrollment[]> {
    return this.scopedSelect<Enrollment>(
      'SELECT * FROM enrollments WHERE course_id=$2 ORDER BY created_at DESC',
      [courseId],
    )
  }

  async get(id: string): Promise<Enrollment | undefined> {
    const rows = await this.scopedSelect<Enrollment>('SELECT * FROM enrollments WHERE id=$2', [id])
    return rows[0]
  }

  async getByToken(token: string): Promise<Enrollment | undefined> {
    const rows = await this.scopedSelect<Enrollment>(
      'SELECT * FROM enrollments WHERE token=$2',
      [token],
    )
    return rows[0]
  }

  async create(input: EnrollmentInput): Promise<Enrollment> {
    const id = nanoid()
    const rows = await this.scopedWrite<Enrollment>(
      `INSERT INTO enrollments (id, location_id, course_id, contact_id, token, status, enrolled_at)
       VALUES ($2,$1,$3,$4,$5,'active',now()) RETURNING *`,
      [id, input.courseId, input.contactId ?? null, input.token],
    )
    return rows[0]!
  }

  /** Flip to completed once the final lesson lands. Idempotent at the call site —
   *  the route only calls this when derived progress reaches 100%. */
  async markCompleted(id: string): Promise<Enrollment | undefined> {
    const rows = await this.scopedWrite<Enrollment>(
      `UPDATE enrollments SET status='completed', completed_at=now()
       WHERE location_id=$1 AND id=$2 RETURNING *`,
      [id],
    )
    return rows[0]
  }

  /** Reopen an enrollment if it dips back below 100% (e.g. a lesson is added
   *  after completion), so `status` never lies about being finished. */
  async markActive(id: string): Promise<Enrollment | undefined> {
    const rows = await this.scopedWrite<Enrollment>(
      `UPDATE enrollments SET status='active', completed_at=NULL
       WHERE location_id=$1 AND id=$2 RETURNING *`,
      [id],
    )
    return rows[0]
  }

  /** Un-enroll a student. The lesson_completions cascade off the enrollment, so
   *  removing it leaves no orphan progress behind. Scoped to this location. */
  async remove(id: string): Promise<void> {
    await this.scopedWrite('DELETE FROM enrollments WHERE location_id=$1 AND id=$2', [id])
  }
}
