import { nanoid } from 'nanoid'
import { LocationScopedRepo } from './base-repo'

export type ReviewRequestStatus = 'pending' | 'completed'

export interface ReviewRequest {
  id: string
  location_id: string
  contact_id: string | null
  channel: string
  token: string
  status: string
  sent_at: string | null
  completed_at: string | null
  created_at: string
}

export interface ReviewRequestInput {
  contactId?: string | null
  channel?: string
  /** The unguessable public-link token, generated by the caller. */
  token: string
}

/**
 * Outbound review requests for one location — the outreach half of the reputation
 * loop, kept separate from the reviews themselves so "requests pending" and a
 * real response rate are honest counts, not guesses. Issuing a request mints a
 * tokenized public link; opening that link and leaving a rating flips the request
 * to `completed`. `getByToken` is the unauthenticated public lookup, still bound
 * to the location in the URL so it stays tenancy-safe.
 */
export class ReviewRequestsRepo extends LocationScopedRepo {
  list(): Promise<ReviewRequest[]> {
    return this.scopedSelect<ReviewRequest>(
      'SELECT * FROM review_requests ORDER BY created_at DESC',
    )
  }

  async getByToken(token: string): Promise<ReviewRequest | undefined> {
    const rows = await this.scopedSelect<ReviewRequest>(
      'SELECT * FROM review_requests WHERE token=$2',
      [token],
    )
    return rows[0]
  }

  async create(input: ReviewRequestInput): Promise<ReviewRequest> {
    const id = nanoid()
    const rows = await this.scopedWrite<ReviewRequest>(
      `INSERT INTO review_requests (id, location_id, contact_id, channel, token, status, sent_at)
       VALUES ($2,$1,$3,$4,$5,'pending',now()) RETURNING *`,
      [id, input.contactId ?? null, input.channel ?? 'sms', input.token],
    )
    return rows[0]!
  }

  /** Mark a request fulfilled once its review lands — drives the response rate. */
  async markCompleted(id: string): Promise<ReviewRequest | undefined> {
    const rows = await this.scopedWrite<ReviewRequest>(
      `UPDATE review_requests SET status='completed', completed_at=now()
       WHERE location_id=$1 AND id=$2 RETURNING *`,
      [id],
    )
    return rows[0]
  }
}
